//
// Created by photovoltex on 3/28/22.
//

#ifndef COMPILERBAU_PKK_DEBUG_H
#define COMPILERBAU_PKK_DEBUG_H

char* DEBUG_TURTLE_TYPE_NAMES[73] = {
        "name_any",
        "name_var",
        "name_path",
        "name_calc",
        "name_glob",
        "name_pvar_ro",
        "name_pvar_rw",
        "name_math_sin",
        "name_math_rand",
        "keyw_dummy",
        "keyw_walk",
        "keyw_jump",
        "keyw_back",
        "keyw_home",
        "keyw_turn",
        "keyw_left",
        "keyw_right",
        "keyw_direction",
        "keyw_clear",
        "keyw_stop",
        "keyw_finish",
        "keyw_path",
        "keyw_color",
        "keyw_store",
        "keyw_in",
        "keyw_add",
        "keyw_to",
        "keyw_sub",
        "keyw_from",
        "keyw_mul",
        "keyw_by",
        "keyw_div",
        "keyw_mark",
        "keyw_if",
        "keyw_then",
        "keyw_else",
        "keyw_endif",
        "keyw_do",
        "keyw_times",
        "keyw_done",
        "keyw_counter",
        "keyw_downto",
        "keyw_step",
        "keyw_while",
        "keyw_repeat",
        "keyw_until",
        "keyw_endpath",
        "keyw_calculation",
        "keyw_returns",
        "keyw_endcalc",
        "keyw_begin",
        "keyw_end",
        "keyw_and",
        "keyw_or",
        "keyw_not",
        "tok_bofeof",
        "oper_const",
        "oper_lpar",
        "oper_rpar",
        "oper_sep",
        "oper_abs",
        "oper_pow",
        "oper_mul",
        "oper_div",
        "oper_add",
        "oper_sub",
        "oper_neg",
        "oper_equ",
        "oper_nequ",
        "oper_less",
        "oper_lequ",
        "oper_grtr",
        "oper_gequ"
};

#endif //COMPILERBAU_PKK_DEBUG_H
